backend:
  name: git-gateway
  branch: master

media_folder: www/public/images
public_folder: '/images'

collections:
  - name: 'decks'
    label: 'Decks'
    label_singular: 'Deck'
    folder: 'www/src/assets/decks'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'text'}